#ifndef PIN_CONFIG_H
#define PIN_CONFIG_H

#define MHZ (1000000)

#define K210_POWER_ELEC
#define PLL0_FREQ 1040 * MHZ
#define CPU_FREQ 520 * MHZ
/*
Pin connection
AD7606     ---- K210

RD/SCLK    <--> AD7606_SCLK
CS         <--> AD7606_CS
DB7/DoutA  <--> AD7606_MISO
CONVST A B <--> AD7606_CONVAB
BUSY       <--> AD7606_BUSY
RESET      <--> AD7606_RESET
*/

#define AD7606_SCLK 18
#define AD7606_CS 19
#define AD7606_MISO 20
#define AD7606_CONVAB 21
#define AD7606_BUSY 22
#define AD7606_RESET 23

// Second AD7606 Pin mapping
#define AD7606_CS_1 24
#define AD7606_BUSY_1 25

// GPIO mapping
#define AD7606_CONVAB_GPIO_NUM 0
#define AD7606_BUSY_GPIO_NUM 1
#define AD7606_RESET_GPIO_NUM 2

#define AD7606_BUSY_GPIO_NUM_1 3

#define AD7606_SPI SPI_DEVICE_0
#define AD7606_SPI_RATE (10 * MHZ)
#define AD7606_SPI_CHIP_SELECT SPI_CHIP_SELECT_0


// PWM Pins
#define PWM_SCLK 26
#define PWM_CS 27
#define PWM_MOSI 28
#define PWM_MISO 29
#define PWM_SYNC 0
#define PWM_RESET 1
#define PWM_DATA_SYNC 2

#define PWM_SPI SPI_DEVICE_1
#define PWM_SPI_RATE (20 * MHZ)
#define PWM_SPI_CHIP_SELECT SPI_CHIP_SELECT_3
#define PWM_SPI_MODE SPI_WORK_MODE_1
#define PWM_SPI_FORMAT SPI_FF_STANDARD

// GPIO mapping
#define PWM_SYNC_GPIO_NUM 4
#define PWM_RESET_GPIO_NUM 5
#define PWM_DATA_SYNC_GPIO_NUM 6
// #define PWM_CS_GPIO_NUM 7

#define PWM_SCLK_FUNC FUNC_SPI1_SCLK
#define PWM_CS_FUNC (FUNC_SPI1_SS3)
// #define PWM_CS_FUNC (FUNC_GPIOHS0 + PWM_CS_GPIO_NUM)
#define PWM_MOSI_FUNC FUNC_SPI1_D0
#define PWM_MISO_FUNC FUNC_SPI1_D1
#define PWM_SYNC_FUNC (FUNC_GPIOHS0 + PWM_SYNC_GPIO_NUM)
#define PWM_RESET_FUNC (FUNC_GPIOHS0 + PWM_RESET_GPIO_NUM)
#define PWM_DATA_SYNC_FUNC (FUNC_GPIOHS0 + PWM_DATA_SYNC_GPIO_NUM)


#ifdef K210_POWER_ELEC
    #define POWER_BANK0_SELECT  SYSCTL_POWER_V33
    #define POWER_BANK1_SELECT  SYSCTL_POWER_V33
    #define POWER_BANK2_SELECT  SYSCTL_POWER_V33
    #define POWER_BANK3_SELECT  SYSCTL_POWER_V33
    #define POWER_BANK4_SELECT  SYSCTL_POWER_V33
    #define POWER_BANK5_SELECT  SYSCTL_POWER_V33
    #define POWER_BANK6_SELECT  SYSCTL_POWER_V18
    #define POWER_BANK7_SELECT  SYSCTL_POWER_V18
#endif

#endif